### ISSUE TITLE
Update to use Node.js 16

### ISSUE THREAD

**Issue by Horschig** [darenm/Setup-VSTest#22]
The current action works fine, but is using Node.js 12, which is deprecated. It needs to be updated to Node.js 16 to stay compatible. 

See this warning
![image](https://user-images.githubusercontent.com/3985329/198106650-668fff8b-adee-40ec-b3c7-c8a578069c15.png)

**Comment by darenm** [comment]
A PR was submitted with that change - I just need to get to building a new package.  I haven't used this for action for a while, so I haven't been on top of it.

**Comment by Horschig** [comment]
Thanks for the quick reply! I just saw this, too, and tried with 

```
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@980eb7e5b062ea5986f9644216c4ae3c55184f12
```

This works fine for me! Guess it is just about making a new release then.

**Comment by darenm** [comment]
Thanks for testing!

**Comment by darenm** [comment]
I pushed out a new release.
