### ISSUE TITLE
Update to Node.js 20

### ISSUE THREAD

**Issue by i2van** [darenm/Setup-VSTest#28]
From GitHub actions build:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: darenm/Setup-VSTest@v1.2, actions/upload-artifact@v3.1.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by darenm** [comment]
i have no plans to continue maintenance of this tool.

**Comment by i2van** [comment]
Workaround for [Windows builds](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#visual-studio-enterprise-2022) that does not require [Setup-VSTest](https://github.com/darenm/Setup-VSTest) can be found [here](https://github.com/i2van/hourglass/blob/5c5f3a5eddae77c65d38e32b5f5ba4a548aecae1/.github/workflows/build.yml#L40); `VS_TEST_CONSOLE_PATH` is set [here](https://github.com/i2van/hourglass/blob/5c5f3a5eddae77c65d38e32b5f5ba4a548aecae1/.github/workflows/build.yml#L10).
