### ISSUE TITLE
The add-path command is deprecated

### ISSUE THREAD

**Issue by ltrzesniewski** [darenm/Setup-VSTest#5]
Using Setup-VSTest generates the following warning:

> Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Please update it to use [Environment Files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) instead (or maybe there's an API for actions to use, I don't know).

**Comment by ltrzesniewski** [comment]
This should be fixed by #4 as @actions/core v1.2.6 changes the implementation of `addPath`.

**Comment by darenm** [comment]
thanks for the issue - I'll take a look.

**Comment by ArchieCoder** [comment]
@ltrzesniewski @darenm Watching since I'm also impacting :)

**Comment by darenm** [comment]
I updated the dependencies and tagged a v1.1 
My builds still threw the warning when I re-ran them. Let me know if you still see it and I will take another look.

**Comment by ArchieCoder** [comment]
Hi, the warning is still there.

![Uploading FC9CE850-6C29-48EF-A4CB-A48B9D25ED78.png…]()

**Comment by ltrzesniewski** [comment]
Same thing here, the warning still appears with v1.1 😕 

I'm not sure if that's related, but I noticed the build CI failed on this version though.

**Comment by darenm** [comment]
Sorry for the run around yesterday - I tried to fix it when I didn't have enough time to do a decent job! Take a look at v1.1.1 - that runs without warnings/errors on my builds now.

**Comment by ltrzesniewski** [comment]
I can confirm that v1.1.1 doesn't output the warning anymore. Thanks! 😄
