### ISSUE TITLE
@v1 does not upgrade to v1.1.1

### ISSUE THREAD

**Issue by aarondandy** [darenm/Setup-VSTest#7]
I am referencing darenm/Setup-VSTest@v1 in my actions yaml and appear to still be getting the older version. This is causing build failures now that the issue resolved in #5 is no longer a warning. I'm not really that knowledgeable about actions but asked @xt0rted and he is talking me through this 😛. Based on [the docs](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) and his experience it sounds like you should tag 379ad01 as 1.0.0 (without a `v` ... or maybe with one?) and move the v1 tag to fbb574e (after maybe tagging it with 1.1.1) 🤷‍♂️.

Error for searchability:
```
Error: Unable to process command '::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-
```

I suppose workarounds for the short term are to change the tag referenced in our actions or set that variable mentioned above 👆

**Comment by darenm** [comment]
That is the point - when you reference **darenm/Setup-VSTest@v1** you are pointing to an explicit tagged version 1 which has old references that have been deprecated. There is a new version which is tagged v1.1.1 that addresses the deprecated packages. If you look at the [marketplace](https://github.com/marketplace/actions/setup-vstest-console-exe) and click **Use latest version** it will show you the code to get the latest version.
![image](https://user-images.githubusercontent.com/1674843/99296198-9bde9280-2803-11eb-8f28-4bd931c94a55.png)

**Comment by aarondandy** [comment]
Would you consider a tag such as `v1-latest` or something to allow getting minor or patch increments?

**Comment by darenm** [comment]
I'm trying to balance my concern about promoting a flawed version that breaks people's builds vs. ease of use.  As I am sure you know, if I move the tag to a broken build, that will mess everyone up and I don't always have the time to jump back in and fix things immediately. That said, I am conscious of the fact that it is desirable for these things to "just work" without everyone having to update their builds every time an author updates their action... So, upon further reflection, I will do as you suggested and move the v1 tag.

As often seems to be the case with these things, I put this together for myself and I'm surprised it has been picked up by others. Microsoft was, at one point, going to subsume this capability into their action (I gave permission) but that hasn't happened as yet.

**Comment by aarondandy** [comment]
Yeah, promoting a breaking change is a good point that wasn't on my mind when I wrote this. It even happened to us last week with `nuget/setup-nuget@v1` via this issue: https://github.com/NuGet/setup-nuget/issues/21 . Another solution sounds like it may be to keep doing fixed explicit version tags and go with [dependabot](https://github.com/xt0rted/problem-matcher/blob/main/.github/dependabot.yml#L4). Ideally it would be *my* choice to do `1.*` while other users could pin to `1.1.1` explicitly but I don't think this system works that way.

**Comment by aarondandy** [comment]
Also interesting when reading the nuget repo, it looks like they have v1 as a branch instead of a tag. I don't think that is explicitly called out in the docs but it must work because I currently use `nuget/setup-nuget@v1` for that.

**Comment by darenm** [comment]
I agree that the versioning for consumers isn't quite a flexible as say other dependency frameworks, but as the convention seems to be that **v1** tags the latest stable version of the v1.* family. 

So... the tag has been moved.
![image](https://user-images.githubusercontent.com/1674843/99299833-07772e80-2809-11eb-88d7-7860fe35128d.png)

**Comment by vweevers** [comment]
@darenm You might like [`additional-tags-action`](https://github.com/vweevers/additional-tags-action) to automate this. Versioning of actions is still awkward (having to overwrite tags, I don't like it) but maybe it'll help. Thanks for Setup-VSTest!

**Comment by darenm** [comment]
I like the suggestion, however my concern about automatically pushing out a bad version still stands. Fortunately, I don't expect much iteration on this action... (famous last words...)
